// Generated by CoffeeScript 1.6.2
(function() {
  var Fibers, csvtojson, fs;

  Fibers = Npm.require('fibers');

  fs = Npm.require('fs');

  csvtojson = Npm.require('csvtojson');

  this.ctc = {
    _csvConverter: new csvtojson.core.Converter(),
    CreateCollection: function(publicFilePath, onComplete) {
      var collection, e;

      collection = new Meteor.Collection(publicFilePath.split("/").pop());
      if (Meteor.isServer) {
        try {
          collection.remove({});
          this.AddCsvToCollection(publicFilePath, collection, onComplete);
        } catch (_error) {
          e = _error;
          console.log(e);
          console.log("ctc.CreateCollection failed path: " + publicFilePath);
        }
      }
      return collection;
    },
    AddCsvToCollection: function(publicFilePath, collection, onComplete) {
      var csvConverter;

      if (Meteor.isServer) {
        csvConverter = new csvtojson.core.Converter();
        csvConverter.on('end_parsed', function(jsonArray) {
          return Fibers(function() {
            var doc, _i, _len;

            for (_i = 0, _len = jsonArray.length; _i < _len; _i++) {
              doc = jsonArray[_i];
              collection.insert(doc);
            }
            return typeof onComplete === "function" ? onComplete(jsonArray) : void 0;
          }).run();
        });
        return fs.createReadStream("../client/app/" + publicFilePath).pipe(csvConverter);
      }
    }
  };

}).call(this);
