// Generated by CoffeeScript 1.4.0

/*
class JsonLoader
# options.path: json file path
# options.indexName: auto index to json array, default is 'id'
# options.onComplete(loader): trigger when load complete
*/


(function() {

  this.JsonLoader = (function() {

    function JsonLoader(options) {
      var _this = this;
      HTTP.get(Meteor.absoluteUrl(options.path), function(error, result) {
        var _ref;
        if ((error != null) || !(result.data != null)) {
          console.log("JsonLoader fail load path: " + path);
          return;
        }
        _this._data = result.data;
        _this.loadIndex(_this._data, (_ref = options.indexName) != null ? _ref : "id");
        return options.onComplete(_this);
      });
    }

    JsonLoader.prototype.loadIndex = function(array, indexName) {
      var obj, _i, _len, _results;
      this._indexes = {};
      _results = [];
      for (_i = 0, _len = array.length; _i < _len; _i++) {
        obj = array[_i];
        if (obj[indexName] != null) {
          _results.push(this._indexes[obj[indexName]] = obj);
        }
      }
      return _results;
    };

    JsonLoader.prototype.objectForIndex = function(index) {
      return this._indexes[index];
    };

    JsonLoader.prototype.getArray = function() {
      return this._data;
    };

    return JsonLoader;

  })();

}).call(this);
